apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  labels:
    app: web-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.19.1
        ports:
        - containerPort: 80

